name: "my hello action"

description: "say hello with GitHub Actions"

inputs:
  first-greeting:
    description: "who would you like to greet in the console"
    required: true
    default: "Cezary"

  second-greeting:
    description: "another person to greet"
    required: true
    default: "Andrew"

  third-greeting:
    description: "a third greeting"
    required: false

runs:
  using: "node12"
  main: "main.js"
